languages:
  JavaScript: true
exclude_paths:
- "jasmine/lib"
engines:
  # ... CONFIG CONTENT ...
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      no-extend-native:
        enabled: false
# ... CONFIG CONTENT ...

